# Generated by Django 2.0.8 on 2018-10-26 06:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название устройства')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='noimage.jpg', upload_to='faces', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Снимок лица',
                'verbose_name_plural': 'Снимки лица',
            },
        ),
        migrations.CreateModel(
            name='Finger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger_num', models.BigIntegerField(null=True, unique=True, verbose_name='Код отпечатка пальца')),
            ],
            options={
                'verbose_name': 'Отпечаток пальца',
                'verbose_name_plural': 'Отпечатки пальцев',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование организации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('middle_name', models.CharField(default='', max_length=200, verbose_name='Отчество')),
                ('card_num', models.CharField(blank=True, max_length=8, null=True, verbose_name='Номер карты')),
                ('person_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер человека')),
                ('birth_date', models.DateTimeField(verbose_name='День рождения')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
            },
        ),
        migrations.CreateModel(
            name='PersonArrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('come_in', models.BooleanField(verbose_name='Зашёл')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', models.ImageField(default='noimage.jpg', upload_to='person_arrivals', verbose_name='Фото')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Device', verbose_name='Устройство')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Person', verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
        migrations.CreateModel(
            name='PersonUnauthorizedEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', models.ImageField(default='noimage.jpg', upload_to='person_unauthorized_arrivals', verbose_name='Фото')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Device', verbose_name='Устройство')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Person', verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'История несанкционированных входов',
                'verbose_name_plural': 'Истории несанкционированных входов',
            },
        ),
        migrations.AddField(
            model_name='finger',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Person', verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='face',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Person', verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Organization', verbose_name='Организация'),
        ),
    ]
