# Generated by Django 2.0.8 on 2018-09-08 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger_hash', models.TextField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Person')),
            ],
        ),
    ]
