# Generated by Django 2.0.8 on 2018-09-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20180908_1449'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faces',
            new_name='Face',
        ),
    ]
