# Generated by Django 2.0.8 on 2018-09-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20180908_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='path',
            field=models.ImageField(upload_to=''),
        ),
    ]
