# Generated by Django 2.0.8 on 2018-09-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20180908_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройство'},
        ),
        migrations.AlterModelOptions(
            name='face',
            options={'verbose_name': 'Снимок лица', 'verbose_name_plural': 'Снимок лица'},
        ),
        migrations.AlterModelOptions(
            name='finger',
            options={'verbose_name': 'Отпечаток пальца', 'verbose_name_plural': 'Отпечаток пальца'},
        ),
        migrations.AlterModelOptions(
            name='personarrival',
            options={'verbose_name': 'История', 'verbose_name_plural': 'История'},
        ),
        migrations.RenameField(
            model_name='face',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='finger',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='personarrival',
            old_name='device_id',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='personarrival',
            old_name='person_id',
            new_name='person',
        ),
    ]
