# Generated by Django 2.0.8 on 2018-09-08 17:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20180908_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название устройства'),
        ),
        migrations.AlterField(
            model_name='face',
            name='path',
            field=models.ImageField(upload_to='', verbose_name='Путь'),
        ),
        migrations.AlterField(
            model_name='face',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Person', verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='finger',
            name='finger_num',
            field=models.BigIntegerField(null=True, unique=True, verbose_name='Код отпечатка пальца'),
        ),
        migrations.AlterField(
            model_name='finger',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Person', verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateTimeField(verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='card_num',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='personarrival',
            name='come_in',
            field=models.BooleanField(verbose_name='Зашел/Вышел'),
        ),
        migrations.AlterField(
            model_name='personarrival',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='personarrival',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Device', verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='personarrival',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Person', verbose_name='ФИО'),
        ),
    ]
