# Generated by Django 2.0.8 on 2018-09-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20180908_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='created_date',
            new_name='created',
        ),
    ]
