# Generated by Django 2.0.8 on 2018-09-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_personunauthorizedentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='personarrival',
            name='image',
            field=models.ImageField(default='/Users/air/Desktop/python-server/mysite/media/noimage.jpg', upload_to='', verbose_name='Фото'),
        ),
    ]
