# Generated by Django 2.0.8 on 2018-09-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_personarrival_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personarrival',
            name='image',
            field=models.ImageField(default='/media/noimage.jpg', upload_to='', verbose_name='Фото'),
        ),
    ]
