# Generated by Django 2.0.8 on 2018-09-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20180911_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personarrival',
            name='image',
            field=models.ImageField(default='/Users/air/Desktop/python-server/mysite/medianoimage.jpg', upload_to='', verbose_name='Фото'),
        ),
    ]
