# Generated by Django 2.0.8 on 2018-09-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_auto_20180911_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personarrival',
            name='image',
            field=models.ImageField(default='media/noimage.jpg', upload_to='', verbose_name='Фото'),
        ),
    ]
