# Generated by Django 2.0.8 on 2018-09-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20180911_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personarrival',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='', verbose_name='Фото'),
        ),
    ]
