# Generated by Django 2.0.8 on 2018-09-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_auto_20180911_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='path',
        ),
        migrations.AddField(
            model_name='face',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='personunauthorizedentry',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='', verbose_name='Фото'),
        ),
    ]
