# Generated by Django 2.0.8 on 2018-09-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_auto_20180911_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='faces', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='personarrival',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='person_arrivals', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='personunauthorizedentry',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='person_unauthorized_arrivals', verbose_name='Фото'),
        ),
    ]
